---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-s3
  namespace: spack
spec:
  secretName: tls-s3
  issuerRef:
    name: letsencrypt
    kind: Issuer
  commonName: s3.spack.io
  dnsNames:
  - s3.spack.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - s3.spack.io
