---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-staging
  namespace: spack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: spack-mysql-staging
