---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-mirror
  namespace: spack
spec:
  secretName: tls-mirror
  issuerRef:
    name: letsencrypt
    kind: Issuer
  commonName: mirror.spack.io
  dnsNames:
  - mirror.spack.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - mirror.spack.io
