---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-www
  namespace: spack
spec:
  secretName: tls-www
  issuerRef:
    name: letsencrypt
    kind: Issuer
  commonName: spack.io
  dnsNames:
  - spack.io
  - www.spack.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.spack.io
      - spack.io
