---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-packages
  namespace: spack
spec:
  secretName: tls-packages
  issuerRef:
    name: letsencrypt
    kind: Issuer
  dnsNames:
  - packages.spack.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - packages.spack.io
