---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-cdash-staging
  namespace: spack
spec:
  secretName: tls-cdash-staging
  issuerRef:
    name: letsencrypt
    kind: Issuer
  dnsNames:
  - cdash.staging.spack.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - cdash.staging.spack.io
